apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/instance: deepSightAI-Trinetra
spec:
  selector:
    app: registry
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: main-api
  labels:
    app.kubernetes.io/name: main-api
    app.kubernetes.io/instance: deepSightAI-Trinetra
spec:
  selector:
    app: main-api
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: extractor
  labels:
    app.kubernetes.io/name: extractor
    app.kubernetes.io/instance: deepSightAI-Trinetra
spec:
  selector:
    app: extractor
  ports:
  - port: 8001
    targetPort: 8001
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: embedder
  labels:
    app.kubernetes.io/name: embedder
    app.kubernetes.io/instance: deepSightAI-Trinetra
spec:
  selector:
    app: embedder
  ports:
  - port: 8001
    targetPort: 8001
    name: http
  type: ClusterIP
